### ISSUE TITLE
Crashes on class declaration with no id

### ISSUE THREAD

**Issue by ef4** [ember-template-imports/ember-template-imports#159]
A class declaration with no id:

```js
import Component from '@glimmer/component';
export default class extends Component {
  <template>hello world</template>
}
```

Causes a crash in the build:

```
Build Error (broccoli-persistent-filter:Babel > [Babel: eti-test]) in eti-test/components/example.js

/Users/edward/hacking/eti-test/eti-test/components/example.js: Property arguments[1] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got undefinedTypeError: /Users/edward/hacking/eti-test/eti-test/components/example.js: Property arguments[1] of CallExpression expected node to be of a type ["Expression","SpreadElement","JSXNamespacedName","ArgumentPlaceholder"] but instead got undefined
    at validate (/Users/edward/hacking/eti-test/node_modules/.pnpm/@babel+types@7.21.5/node_modules/@babel/types/lib/definitions/utils.js:112:11)
    at validator (/Users/edward/hacking/eti-test/node_modules/.pnpm/@babel+types@7.21.5/node_modules/@babel/types/lib/definitions/utils.js:88:7)
    at Object.validate (/Users/edward/hacking/eti-test/node_modules/.pnpm/@babel+types@7.21.5/node_modules/@babel/types/lib/definitions/utils.js:188:7)
    at validateField (/Users/edward/hacking/eti-test/node_modules/.pnpm/@babel+types@7.21.5/node_modules/@babel/types/lib/validators/validate.js:21:9)
    at validate (/Users/edward/hacking/eti-test/node_modules/.pnpm/@babel+types@7.21.5/node_modules/@babel/types/lib/validators/validate.js:15:3)
```

**Comment by NullVoxPopuli** [comment]
Should be resolved in v4. Thanks for reporting!
If this is still an issue, lemme know and we can reopen.
