### ISSUE TITLE
duplicate babel plugin when used in an app that consumes in addon that uses ember-template-imports

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-template-imports/ember-template-imports#28]
Error:
```
Uncaught (in promise) 
Error: Could not find module `<addon-name>/components/<component-name-a>`
 imported from `<app-name>/components/<component-name-a>
```
it's weird to me how it's looking up `<app-name>/components/<component-name-a>`, but I guess if the app is using the globals resolver, I guess that makes sense. _but_, I'd expect the template-imports transform to convert `<component-name-a>` to be compat with the old way of doing things for the app to consume?

------------------------

`ember-template-imports` is in the addon's `dependencies`

**Comment by NullVoxPopuli** [comment]
j/k, I needed to run yarn :sweat_smile: 
this error doesn't occur when ember-template-imports is actually in `node_modules` :upside_down_face: 

Instead, I get: 
```

=================================================================================

ENV Summary:

  TIME: Tue Dec 21 2021 11:05:43 GMT-0500 (Eastern Standard Time)
  TITLE: ember
  ARGV:
  - 🏠/.volta/tools/image/node/16.13.1/bin/node
  - /✂️/<monorepo>/<app>/node_modules/.bin/ember
  - serve
  - --watcher
  - polling
  - --ssl
  - false
  EXEC_PATH: 🏠/.volta/tools/image/node/16.13.1/bin/node
  TMPDIR: /tmp
  SHELL: /bin/bash
  PATH:
  - 🏠/.volta/tools/image/yarn/1.22.17/bin
  - 🏠/.volta/tools/image/node/16.13.1/bin
  - 🏠/.volta/bin
  - 🏠/.pyenv/plugins/pyenv-virtualenv/shims
  - 🏠/.pyenv/shims
  - 🏠/.pyenv/bin
  - /✂️/scripts/
  - 🏠/Applications
  - 🏠/apps/phantomjs/bin
  - 🏠/scripts/system-utils
  - 🏠/scripts/git
  - 🏠/scripts/rails
  - 🏠/scripts
  - 🏠/.volta/bin
  - 🏠/.local/bin
  - /usr/local/sbin
  - /usr/local/bin
  - /usr/sbin
  - /usr/bin
  - /sbin
  - /bin
  - /usr/games
  - /usr/local/games
  - /snap/bin
  - 🏠/.fzf/bin
  - /usr/lib/go-1.13/bin
  - /bin
  - 🏠/go/bin
  PLATFORM: linux x64
  FREEMEM: 819068928
  TOTALMEM: 18851196928
  UPTIME: 8276.76
  LOADAVG: 0.76,1.31,1.35
  CPUS:
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  - Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz - 2400
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.18.1
  - brotli: 1.0.9
  - cldr: 39.0
  - icu: 69.1
  - llhttp: 6.0.4
  - modules: 93
  - napi: 8
  - nghttp2: 1.45.1
  - nghttp3: 0.1.0-DEV
  - ngtcp2: 0.1.0-DEV
  - node: 16.13.1
  - openssl: 1.1.1l+quic
  - tz: 2021a
  - unicode: 13.0
  - uv: 1.42.0
  - v8: 9.4.146.24-node.14
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  }
]
    at assertNoDuplicates (/✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:239:13)
    at createDescriptors (/✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:147:3)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:138:17)
    at createPluginDescriptors.next (<anonymous>)
    at /✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:94:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/✂️/<monorepo>/node_modules/@babel/core/lib/gensync-utils/async.js:25:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/✂️/<monorepo>/node_modules/gensync/index.js:251:28)
  - code: [undefined]
  - codeFrame: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  }
]
  - errorMessage: <addon-name>/test-support/-private/card.ts: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  }
]
        in /tmp/broccoli-61270RCr54gd8tFxg/out-0102-funnel
        at broccoli-persistent-filter:Babel > [Babel: <addon-name>] (Babel: <addon-name>)
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: <addon-name>/test-support/-private/card.ts
    - line: [undefined]
    - treeDir: /tmp/broccoli-61270RCr54gd8tFxg/out-0102-funnel
  - message: <addon-name>/test-support/-private/card.ts: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  }
]
        in /tmp/broccoli-61270RCr54gd8tFxg/out-0102-funnel
        at broccoli-persistent-filter:Babel > [Babel: <addon-name>] (Babel: <addon-name>)
  - name: Error
  - nodeAnnotation: Babel: <addon-name>
  - nodeName: broccoli-persistent-filter:Babel > [Babel: <addon-name>]
  - originalErrorMessage: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  }
]
  - stack: Error: Duplicate plugin/preset detected.
If you'd like to use two separate instances of a plugin,
they need separate names, e.g.

  plugins: [
    ['some-plugin', {}],
    ['some-plugin', {}, 'some unique name'],
  ]

Duplicates detected are:
[
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  },
  {
    "alias": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
    "dirname": "/✂️/<monorepo>/<app>",
    "ownPass": false,
    "file": {
      "request": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js",
      "resolved": "/✂️/<monorepo>/node_modules/ember-template-imports/src/babel-plugin.js"
    }
  }
]
    at assertNoDuplicates (/✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:239:13)
    at createDescriptors (/✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:147:3)
    at createDescriptors.next (<anonymous>)
    at createPluginDescriptors (/✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:138:17)
    at createPluginDescriptors.next (<anonymous>)
    at /✂️/<monorepo>/node_modules/@babel/core/lib/config/config-descriptors.js:94:32
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/✂️/<monorepo>/node_modules/@babel/core/lib/gensync-utils/async.js:25:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/✂️/<monorepo>/node_modules/gensync/index.js:251:28)

=================================================================================
```
