### ISSUE TITLE
breaks with babel sourceMaps: 'inline'

### ISSUE THREAD

**Issue by luxzeitlos** [ember-template-imports/ember-template-imports#43]
The build breaks when `sourceMaps: 'inline'` is specified in the the `ember-cli-build.js`:

```js
  let app = new EmberApp(defaults, {
    babel: {
      sourceMaps: 'inline',
    },
  });
```

```
Build Error (broccoli-persistent-filter:Babel > [Babel: test-template-imports]) in test-template-imports/templates/application.js

/home/lux/git/contrib/test-template-imports/test-template-imports/templates/application.js: Cannot read properties of undefined (reading 'length')TypeError: /home/lux/git/contrib/test-template-imports/test-template-imports/templates/application.js: Cannot read properties of undefined (reading 'length')
    at memoizedBinarySearch (/home/lux/git/contrib/test-template-imports/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:138:29)
    at traceSegmentInternal (/home/lux/git/contrib/test-template-imports/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:506:21)
    at Object.exports.traceSegment (/home/lux/git/contrib/test-template-imports/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:393:20)
    at originalPositionFor (/home/lux/git/contrib/test-template-imports/node_modules/@ampproject/remapping/dist/remapping.umd.js:90:38)
    at traceMappings (/home/lux/git/contrib/test-template-imports/node_modules/@ampproject/remapping/dist/remapping.umd.js:59:30)
    at remapping (/home/lux/git/contrib/test-template-imports/node_modules/@ampproject/remapping/dist/remapping.umd.js:203:30)
    at mergeSourceMap (/home/lux/git/contrib/test-template-imports/node_modules/@babel/core/lib/transformation/file/merge-map.js:22:30)
    at generateCode (/home/lux/git/contrib/test-template-imports/node_modules/@babel/core/lib/transformation/file/generate.js:76:41)
    at run (/home/lux/git/contrib/test-template-imports/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)


Stack Trace and Error Report: /tmp/error.dump.67aa97b8198d8cbc18d5fe1eeeea2982.log

```

[reproduction](https://github.com/luxferresum/test-template-imports)

**Comment by bartocc** [comment]
@luxferresum have you found a solution to this?

**Comment by chriskrycho** [comment]
Does this still reproduce on the latest version (just released a little while ago)? I would assume it does—none of those changes were intended or likely to fix it—but wanted to double check.

**Comment by bartocc** [comment]
Hi @chriskrycho 

Yes, the issue is still present with ember-template-imports@3.1.2.

I should add that the app builds correctly when using Embroider, even with the following Webpack sourcemaps config:

```js
  const { Webpack } = require('@embroider/webpack');
  return require('@embroider/compat').compatBuild(app, Webpack, {
    packagerOptions: {
      webpackConfig: {
        devtool: 'source-map',
      },
    },
  });
```

**Comment by tcjr** [comment]
I am having this problem with the latest ember-template-imports version 3.4.2.

1. Added ember-template-imports to a big project already using embroider with `devtool: 'source-map'`.
2. Created this component (hello.gts):
```gts
import Component from '@glimmer/component';

export default class HelloComponent extends Component {
  <template>
    <h1>Hello</h1>
  </template>
}
```
The build fails with this:

```
webpack 5.79.0 compiled with 1 error and 1 warning in 39347 ms
Build Error (PackagerRunner) in components/hello.ts

Module build failed (from ../../../../../../../../Users/tcjr/dev/PROJECT/node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
$TMPDIR/embroider/735ce2/components/hello.ts/hello.ts: Cannot read properties of undefined (reading 'length')

    at memoizedBinarySearch (/Users/tcjr/dev/PROJECT/node_modules/@ampproject/remapping/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:138:29)
    at traceSegmentInternal (/Users/tcjr/dev/PROJECT/node_modules/@ampproject/remapping/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:513:21)
    at Object.exports.traceSegment (/Users/tcjr/dev/PROJECT/node_modules/@ampproject/remapping/node_modules/@jridgewell/trace-mapping/dist/trace-mapping.umd.js:393:20)
    at originalPositionFor (/Users/tcjr/dev/PROJECT/node_modules/@ampproject/remapping/dist/remapping.umd.js:90:38)
    at traceMappings (/Users/tcjr/dev/PROJECT/node_modules/@ampproject/remapping/dist/remapping.umd.js:59:30)
    at remapping (/Users/tcjr/dev/PROJECT/node_modules/@ampproject/remapping/dist/remapping.umd.js:203:30)
    at mergeSourceMap (/Users/tcjr/dev/PROJECT/node_modules/@babel/core/lib/transformation/file/merge-map.js:22:30)
    at generateCode (/Users/tcjr/dev/PROJECT/node_modules/@babel/core/lib/transformation/file/generate.js:76:41)
    at run (/Users/tcjr/dev/PROJECT/node_modules/@babel/core/lib/transformation/index.js:55:33)
    at run.next (<anonymous>)


Stack Trace and Error Report: /var/folders/27/fwb98ss15l3gp6lx1jyd22n00000gn/T/error.dump.6a9f7e2170359a60e896908d2085fffc.log
```

If I temporarily turn off source maps, the build works.

Also, just like [in the other very similar issue](https://github.com/ember-template-imports/ember-template-imports/issues/48), it looks like pinning the version of @babel/generator to a specific version seems to resolve the issue.  In my project, I added `"**/@babel/generator": "~7.23.0"` to "resolutions" in package.json.  

This app had 7 unique versions of @babel/generator (7.18.2, 7.20.5, 7.20.7, 7.21.1, 7.21.4, 7.22.7, 7.22.9) in 18 dependencies. I am not entirely sure how this works, so I hope it didn't break anything else.
